[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Author Name <author_name@example.com>"]

# The title and description fields are primarly for displaying extension info in UI
title = "USD Connect Window"
description="A window to set usd connection"

# Keywords for the extension
keywords = ['window', 'usd', 'connect']

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.rst"

category = "Rendering"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.svg"

[dependencies]
"omni.kit.menu.utils" = {}

# Main python module this extension provides, it will be publicly available as "import omni.kit.browser.sky".
[[python.module]]
name = "omni.kit.window.usd_connect"

[[test]]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
    "omni.kit.viewport.window",
    "omni.kit.ui_test",
]
args = [
    "--no-window",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/app/asyncRendering=false",
    "--/app/fastShutdown=true",
    "--/app/window/width=1280",
    "--/app/window/height=720",
]